// Generated by CoffeeScript 1.3.1

describe("Declaration", function() {
  it("can parse return type", function() {
    var dec;
    dec = new Declaration("- (NSData *)dataUsingEncoding:(NSStringEncoding)encoding allowLossyConversion:(BOOL)flag)");
    return expect(dec.return_type()).toEqual("NSData *");
  });
  return it("can parse method name", function() {
    var dec;
    dec = new Declaration("- (NSData *)dataUsingEncoding:(NSStringEncoding)encoding allowLossyConversion:(BOOL)flag)");
    return expect(dec.method_name()).toEqual("dataUsingEncoding");
  });
});
