// Generated by CoffeeScript 1.3.1
var Declaration;

Declaration = (function() {

  Declaration.name = 'Declaration';

  function Declaration(declaration) {
    this.declaration = declaration;
  }

  Declaration.prototype.return_type = function() {
    var pattern;
    pattern = /.\((.+?)\)/;
    return this.declaration.match(pattern)[1];
  };

  Declaration.prototype.method_name = function() {
    var pattern;
    pattern = /.+?\)(.+?):/;
    return this.declaration.match(pattern)[1];
  };

  return Declaration;

})();
